server:
  port: ${SERVER_PORT:8080}

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${THE_MAIL_SENDER}
    password: ${THE_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true